- id: circleci_validate
  name: Validate CircleCI config
  description: This hook validate CircleCI config 
  entry: circleci_validate.sh
  language: script
  files: ^.circleci/config.yml$
- id: gitlabci_validate
  name: Validate GitlabCI config
  description: This hook validate GitlabCI config
  entry: gitlabci_validate.sh
  language: script
  files: ^.gitlab-ci.yml$
- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: helmlint.sh
  language: script
  files: \.((ya?ml)|(tpl))$
  require_serial: true
